PYTHON_EXEC=$1
ROOT_PATH=$2
SAVE_PATH=$3

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.Crossformer" --model-hyper-params '{"d_ff": 256, "d_model": 128, "horizon": 96, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/Crossformer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size": 8, "d_ff": 2048, "d_model": 512, "horizon": 96, "lr": 0.005, "norm": true, "seq_len": 336}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/DLinear"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "duet.DUET" --model-hyper-params '{"CI": 1, "batch_size": 128, "d_ff": 512, "d_model": 512, "dropout": 0.2, "e_layers": 3, "factor": 3, "fc_dropout": 0.05, "hidden_size": 128, "horizon": 96, "k": 3, "loss": "MAE", "lr": 0.0001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 100, "num_experts": 5, "patch_len": 48, "patience": 5, "seq_len": 96}' --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/DUET"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.FEDformer" --model-hyper-params '{"batch_size": 8, "d_ff": 256, "d_model": 128, "dropout": 0.05, "factor": 3, "horizon": 96, "moving_avg": 25, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/FEDformer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.FiLM" --model-hyper-params '{"d_ff": 2048, "d_model": 512, "dropout": 0.05, "factor": 3, "horizon": 96, "lr": 0.001, "moving_avg": 25, "norm": true, "num_epochs": 20, "patience": 20, "seq_len": 512}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/FiLM"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "fits.FITS" --model-hyper-params '{"H_order": 6, "batch_size": 32, "horizon": 96, "loss": "MSE", "lr": 0.005, "norm": true, "patience": 10, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/FITS"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.Informer" --model-hyper-params '{"d_ff": 256, "d_model": 128, "horizon": 96, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/Informer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.iTransformer" --model-hyper-params '{"d_ff": 128, "d_model": 128, "e_layers": 1, "horizon": 96, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/iTransformer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MICN" --model-hyper-params '{"d_ff": 512, "d_model": 512, "dropout": 0.05, "horizon": 96, "lr": 0.001, "moving_avg": 25, "norm": true, "num_epochs": 15, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/MICN"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.NLinear" --model-hyper-params '{"d_ff": 2048, "d_model": 512, "factor": 3, "horizon": 96, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/NLinear"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.Nonstationary_Transformer" --model-hyper-params '{"d_ff": 64, "d_model": 32, "horizon": 96, "norm": true, "p_hidden_dims": [256, 256], "p_hidden_layers": 2, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/Nonstationary_Transformer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff": 256, "d_model": 128, "horizon": 96, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/PatchTST"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "pathformer.Pathformer" --model-hyper-params '{"batch_norm": 0, "batch_size": 128, "d_ff": 32, "d_model": 16, "horizon": 96, "k": 1, "layer_nums": 1, "learning_rate": 0.0001, "lradj": "TST", "norm": true, "num_nodes": 8, "patch_size_list": [[16, 8, 12, 24]], "residual_connection": 1, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/Pathformer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "pdf.PDF" --model-hyper-params '{"batch_size": 64, "d_ff": 256, "d_model": 128, "dropout": 0.3, "e_layers": 1, "fc_dropout": 0.15, "horizon": 96, "kernel_list": [3, 7, 9, 11], "n_head": 32, "norm": true, "patch_len": [1], "patience": 5, "pc_start": 0.2, "period": [24], "seq_len": 96, "stride": [1], "train_epochs": 20}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/PDF"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "darts.RegressionModel" --model-hyper-params '{"lags": 96, "norm": true, "output_chunk_length": 1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/RegressionModel"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "darts.RNNModel" --model-hyper-params '{"input_chunk_length": 96, "norm": true, "output_chunk_length": 336}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/RNNModel"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "darts.TCNModel" --model-hyper-params '{"input_chunk_length": 512, "n_epochs": 10, "norm": true, "output_chunk_length": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/TCNModel"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.TimeMixer" --model-hyper-params '{"batch_size": 16, "d_ff": 32, "d_model": 16, "down_sampling_layer": 3, "down_sampling_window": 2, "e_layers": 2, "horizon": 96, "lr": 0.01, "norm": true, "num_epochs": 20, "patience": 10, "seq_len": 336}' --adapter "transformer_adapter" --deterministic "full" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/TimeMixer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.TimesNet" --model-hyper-params '{"d_ff": 128, "d_model": 64, "factor": 3, "horizon": 96, "norm": true, "seq_len": 96, "top_k": 5}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/TimesNet"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.Triformer" --model-hyper-params '{"d_ff": 64, "d_model": 32, "horizon": 96, "norm": true, "seq_len": 96}' --adapter "transformer_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/Triformer"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "self_impl.VAR_model" --model-hyper-params '{}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/VAR_model"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "hidden_size": 64, "horizon": 96, "lr": 0.0005, "norm": true, "seq_len": 512}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/Amplifier"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size": 32, "begin_order": 0, "d_ff": 32, "d_model": 16, "down_sampling_layer": 2, "down_sampling_window": 2, "e_layers": 2, "horizon": 96, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 3, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/TimeKAN"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "patchmlp.PatchMLP" --model-hyper-params '{"data": "custom", "seq_len": 512, "horizon": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/PatchMLP"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 128, "lr": 0.0005, "num_epochs": 20, "patience": 3, "horizon": 96,  "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "$SAVE_PATH/xPatch"

"$PYTHON_EXEC" "$ROOT_PATH"/scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "hdmixer.HDMixer" --model-hyper-params '{"n_heads":4, "d_model": 16, "d_ff":32, "dropout":0.8, "e_layers":1, "batch_size":256, "lr": 5e-4, "fc_dropout":0.3, "head_dropout":0, "num_epochs": 50, "patience": 3, "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 0 --timeout 60000 --save-path "$SAVE_PATH/HDMixer"
